trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    wget https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
    unzip terraform_1.7.5_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform -version
  displayName: Install Terraform

- script: |
    cd terraform
    terraform init
  displayName: Terraform Init

- script: |
    cd terraform
    terraform validate
  displayName: Terraform Validate

- script: |
    cd terraform
    terraform plan
  displayName: Terraform Plan