spring.datasource.url=jdbc:postgresql://myapp-postgres-server.postgres.database.azure.com:5432/employeedb?sslmode=require
spring.datasource.username=manoj
spring.datasource.password=Chawakula%400113

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080